# Generated by Django 5.1.5 on 2025-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
