# Generated by Django 5.1.5 on 2025-02-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('under_review', 'Em Análise'), ('rejected', 'Rejeitado')], default='under_review', max_length=15),
        ),
    ]
