--
-- PostgreSQL database dump
--

-- Dumped from database version 14.13 (Homebrew)
-- Dumped by pg_dump version 17.0

-- Started on 2025-03-06 09:10:33 -03

--SET statement_timeout = 0;
--SET lock_timeout = 0;
--SET idle_in_transaction_session_timeout = 0;
--SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 21061)
-- Name: alugae; Type: SCHEMA; Schema: -; Owner: felixmiranda
--

CREATE SCHEMA alugae;


ALTER SCHEMA alugae OWNER TO postgres;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: felixmiranda
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 21283)
-- Name: account_emailaddress; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE alugae.account_emailaddress OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 21282)
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 21291)
-- Name: account_emailconfirmation; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE alugae.account_emailconfirmation OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 21290)
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 21239)
-- Name: user_groups; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.user_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE alugae.user_groups OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 21238)
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.accounts_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 21223)
-- Name: user; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae."user" (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254),
    phone character varying(15),
    cpf character varying(14),
    address text
);


ALTER TABLE alugae."user" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 21222)
-- Name: accounts_customuser_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.accounts_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 21245)
-- Name: user_user_permissions; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.user_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE alugae.user_user_permissions OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 21244)
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.accounts_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 21521)
-- Name: tenant; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.tenant (
    id bigint NOT NULL,
    marital_status character varying(20),
    profession character varying(100),
    user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    landlord_id bigint NOT NULL
);


ALTER TABLE alugae.tenant OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 21520)
-- Name: accounts_tenant_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.tenant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.accounts_tenant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 21689)
-- Name: adoption_codes; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.adoption_codes (
    id integer NOT NULL,
    landlord_id integer NOT NULL,
    code character varying(5) NOT NULL
);


ALTER TABLE alugae.adoption_codes OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 21688)
-- Name: adoption_codes_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

CREATE SEQUENCE alugae.adoption_codes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE alugae.adoption_codes_id_seq OWNER TO postgres;

--
-- TOC entry 3966 (class 0 OID 0)
-- Dependencies: 250
-- Name: adoption_codes_id_seq; Type: SEQUENCE OWNED BY; Schema: alugae; Owner: felixmiranda
--

ALTER SEQUENCE alugae.adoption_codes_id_seq OWNED BY alugae.adoption_codes.id;


--
-- TOC entry 217 (class 1259 OID 21183)
-- Name: auth_group; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE alugae.auth_group OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 21182)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 21191)
-- Name: auth_group_permissions; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE alugae.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 21190)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 21177)
-- Name: auth_permission; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE alugae.auth_permission OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 21176)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 21326)
-- Name: django_admin_log; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE alugae.django_admin_log OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 21325)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 21169)
-- Name: django_content_type; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE alugae.django_content_type OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 21168)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 21161)
-- Name: django_migrations; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE alugae.django_migrations OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 21160)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 21346)
-- Name: django_session; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE alugae.django_session OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 21356)
-- Name: django_site; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE alugae.django_site OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 21355)
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 21625)
-- Name: landlord; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.landlord (
    id integer NOT NULL,
    user_id integer NOT NULL,
    marital_status character varying(20),
    profession character varying(100),
    date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    pix_key character varying(255)
);


ALTER TABLE alugae.landlord OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 21624)
-- Name: landlord_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

CREATE SEQUENCE alugae.landlord_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE alugae.landlord_id_seq OWNER TO postgres;

--
-- TOC entry 3967 (class 0 OID 0)
-- Dependencies: 248
-- Name: landlord_id_seq; Type: SEQUENCE OWNED BY; Schema: alugae; Owner: felixmiranda
--

ALTER SEQUENCE alugae.landlord_id_seq OWNED BY alugae.landlord.id;


--
-- TOC entry 262 (class 1259 OID 21839)
-- Name: payment; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.payment (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    transaction_id character varying(35) NOT NULL,
    payer_name character varying(255) NOT NULL,
    receiver_name character varying(255) NOT NULL,
    receiver_pix_key character varying(255) NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    payment_status character varying(15) NOT NULL,
    validation_notes text,
    created_at timestamp with time zone NOT NULL,
    contract_id bigint NOT NULL,
    landlord_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    unit_id bigint NOT NULL,
    extracted_text text
);


ALTER TABLE alugae.payment OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 21838)
-- Name: payment_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 21463)
-- Name: property; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.property (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    complement character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_standalone boolean NOT NULL,
    landlord_id bigint NOT NULL,
    number character varying(10) NOT NULL,
    state character varying(50) NOT NULL,
    street character varying(255) NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    zip_code character varying(20) NOT NULL
);


ALTER TABLE alugae.property OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 21462)
-- Name: properties_property_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.property ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.properties_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 21770)
-- Name: rent_clause; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.rent_clause (
    id bigint NOT NULL,
    content text NOT NULL,
    added_by_id bigint,
    contract_id bigint NOT NULL
);


ALTER TABLE alugae.rent_clause OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 21769)
-- Name: rent_clause_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.rent_clause ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.rent_clause_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 21739)
-- Name: rent_contract; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.rent_contract (
    id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    rent_value numeric(10,2) NOT NULL,
    payment_due_date integer NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    landlord_id bigint NOT NULL,
    template_id bigint,
    tenant_id bigint NOT NULL,
    unit_id bigint NOT NULL,
    CONSTRAINT rent_contract_payment_due_date_check CHECK ((payment_due_date >= 0))
);


ALTER TABLE alugae.rent_contract OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 21738)
-- Name: rent_contract_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.rent_contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.rent_contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 21754)
-- Name: rent_document; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.rent_document (
    id bigint NOT NULL,
    file character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    contract_id bigint NOT NULL
);


ALTER TABLE alugae.rent_document OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 21753)
-- Name: rent_document_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.rent_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.rent_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 21746)
-- Name: rent_template; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.rent_template (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    content text NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint
);


ALTER TABLE alugae.rent_template OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 21745)
-- Name: rent_template_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.rent_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.rent_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 21365)
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE alugae.socialaccount_socialaccount OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 21364)
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 21373)
-- Name: socialaccount_socialapp; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE alugae.socialaccount_socialapp OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 21372)
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 21379)
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE alugae.socialaccount_socialapp_sites OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 21378)
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.socialaccount_socialapp_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.socialaccount_socialapp_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 21385)
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE alugae.socialaccount_socialtoken OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 21384)
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE alugae.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alugae.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 21471)
-- Name: unit; Type: TABLE; Schema: alugae; Owner: felixmiranda
--

CREATE TABLE alugae.unit (
    deposit_amount numeric(10,2),
    monthly_rent numeric(10,2) NOT NULL,
    move_in_date date,
    move_out_date date,
    status character varying(20) NOT NULL,
    tenant_id bigint,
    unit_number character varying(50) NOT NULL,
    property_id integer,
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE alugae.unit OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 21726)
-- Name: unit_id_seq; Type: SEQUENCE; Schema: alugae; Owner: felixmiranda
--

CREATE SEQUENCE alugae.unit_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE alugae.unit_id_seq OWNER TO postgres;

--
-- TOC entry 3968 (class 0 OID 0)
-- Dependencies: 252
-- Name: unit_id_seq; Type: SEQUENCE OWNED BY; Schema: alugae; Owner: felixmiranda
--

ALTER SEQUENCE alugae.unit_id_seq OWNED BY alugae.unit.id;


--
-- TOC entry 264 (class 1259 OID 21906)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: felixmiranda
--

CREATE TABLE IF NOT EXISTS public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 21905)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: felixmiranda
--

-- ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.django_migrations_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


--
-- TOC entry 3640 (class 2604 OID 21692)
-- Name: adoption_codes id; Type: DEFAULT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.adoption_codes ALTER COLUMN id SET DEFAULT nextval('alugae.adoption_codes_id_seq'::regclass);


--
-- TOC entry 3638 (class 2604 OID 21628)
-- Name: landlord id; Type: DEFAULT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.landlord ALTER COLUMN id SET DEFAULT nextval('alugae.landlord_id_seq'::regclass);


--
-- TOC entry 3635 (class 2604 OID 21727)
-- Name: unit id; Type: DEFAULT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.unit ALTER COLUMN id SET DEFAULT nextval('alugae.unit_id_seq'::regclass);


--
-- TOC entry 3694 (class 2606 OID 21287)
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- TOC entry 3697 (class 2606 OID 21316)
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- TOC entry 3703 (class 2606 OID 21297)
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- TOC entry 3705 (class 2606 OID 21295)
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- TOC entry 3667 (class 2606 OID 21237)
-- Name: user accounts_customuser_cpf_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae."user"
    ADD CONSTRAINT accounts_customuser_cpf_key UNIQUE (cpf);


--
-- TOC entry 3670 (class 2606 OID 21233)
-- Name: user accounts_customuser_email_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae."user"
    ADD CONSTRAINT accounts_customuser_email_key UNIQUE (email);


--
-- TOC entry 3681 (class 2606 OID 21255)
-- Name: user_groups accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_groups
    ADD CONSTRAINT accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq UNIQUE (customuser_id, group_id);


--
-- TOC entry 3684 (class 2606 OID 21243)
-- Name: user_groups accounts_customuser_groups_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_groups
    ADD CONSTRAINT accounts_customuser_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3673 (class 2606 OID 21235)
-- Name: user accounts_customuser_phone_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae."user"
    ADD CONSTRAINT accounts_customuser_phone_key UNIQUE (phone);


--
-- TOC entry 3675 (class 2606 OID 21229)
-- Name: user accounts_customuser_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae."user"
    ADD CONSTRAINT accounts_customuser_pkey PRIMARY KEY (id);


--
-- TOC entry 3686 (class 2606 OID 21269)
-- Name: user_user_permissions accounts_customuser_user_customuser_id_permission_9632a709_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_user_permissions
    ADD CONSTRAINT accounts_customuser_user_customuser_id_permission_9632a709_uniq UNIQUE (customuser_id, permission_id);


--
-- TOC entry 3690 (class 2606 OID 21249)
-- Name: user_user_permissions accounts_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_user_permissions
    ADD CONSTRAINT accounts_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3678 (class 2606 OID 21231)
-- Name: user accounts_customuser_username_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae."user"
    ADD CONSTRAINT accounts_customuser_username_key UNIQUE (username);


--
-- TOC entry 3745 (class 2606 OID 21525)
-- Name: tenant accounts_tenant_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.tenant
    ADD CONSTRAINT accounts_tenant_pkey PRIMARY KEY (id);


--
-- TOC entry 3747 (class 2606 OID 21527)
-- Name: tenant accounts_tenant_user_id_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.tenant
    ADD CONSTRAINT accounts_tenant_user_id_key UNIQUE (user_id);


--
-- TOC entry 3754 (class 2606 OID 21881)
-- Name: adoption_codes adoption_codes_code_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.adoption_codes
    ADD CONSTRAINT adoption_codes_code_key UNIQUE (code);


--
-- TOC entry 3756 (class 2606 OID 21888)
-- Name: adoption_codes adoption_codes_landlord_id_d0575cd2_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.adoption_codes
    ADD CONSTRAINT adoption_codes_landlord_id_d0575cd2_uniq UNIQUE (landlord_id);


--
-- TOC entry 3758 (class 2606 OID 21697)
-- Name: adoption_codes adoption_codes_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.adoption_codes
    ADD CONSTRAINT adoption_codes_pkey PRIMARY KEY (id);


--
-- TOC entry 3656 (class 2606 OID 21220)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3661 (class 2606 OID 21206)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3664 (class 2606 OID 21195)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3658 (class 2606 OID 21187)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3651 (class 2606 OID 21197)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3653 (class 2606 OID 21181)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3708 (class 2606 OID 21333)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3646 (class 2606 OID 21175)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3648 (class 2606 OID 21173)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3644 (class 2606 OID 21167)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

 ALTER TABLE ONLY alugae.django_migrations
     ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3712 (class 2606 OID 21352)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3716 (class 2606 OID 21362)
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- TOC entry 3718 (class 2606 OID 21360)
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- TOC entry 3750 (class 2606 OID 21631)
-- Name: landlord landlord_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.landlord
    ADD CONSTRAINT landlord_pkey PRIMARY KEY (id);


--
-- TOC entry 3752 (class 2606 OID 21633)
-- Name: landlord landlord_user_id_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.landlord
    ADD CONSTRAINT landlord_user_id_key UNIQUE (user_id);


--
-- TOC entry 3778 (class 2606 OID 21845)
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- TOC entry 3782 (class 2606 OID 21847)
-- Name: payment payment_transaction_id_key; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.payment
    ADD CONSTRAINT payment_transaction_id_key UNIQUE (transaction_id);


--
-- TOC entry 3739 (class 2606 OID 21469)
-- Name: property properties_property_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.property
    ADD CONSTRAINT properties_property_pkey PRIMARY KEY (id);


--
-- TOC entry 3774 (class 2606 OID 21776)
-- Name: rent_clause rent_clause_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_clause
    ADD CONSTRAINT rent_clause_pkey PRIMARY KEY (id);


--
-- TOC entry 3761 (class 2606 OID 21744)
-- Name: rent_contract rent_contract_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_contract
    ADD CONSTRAINT rent_contract_pkey PRIMARY KEY (id);


--
-- TOC entry 3770 (class 2606 OID 21758)
-- Name: rent_document rent_document_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_document
    ADD CONSTRAINT rent_document_pkey PRIMARY KEY (id);


--
-- TOC entry 3767 (class 2606 OID 21752)
-- Name: rent_template rent_template_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_template
    ADD CONSTRAINT rent_template_pkey PRIMARY KEY (id);


--
-- TOC entry 3720 (class 2606 OID 21371)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- TOC entry 3722 (class 2606 OID 21433)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- TOC entry 3727 (class 2606 OID 21403)
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- TOC entry 3725 (class 2606 OID 21377)
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- TOC entry 3729 (class 2606 OID 21383)
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- TOC entry 3735 (class 2606 OID 21393)
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- TOC entry 3737 (class 2606 OID 21391)
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 3742 (class 2606 OID 21729)
-- Name: unit unit_pkey; Type: CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.unit
    ADD CONSTRAINT unit_pkey PRIMARY KEY (id);


--
-- TOC entry 3785 (class 2606 OID 21912)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: felixmiranda
--

-- ALTER TABLE ONLY public.django_migrations
--     ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3691 (class 1259 OID 21319)
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX account_emailaddress_email_03be32b2 ON alugae.account_emailaddress USING btree (email);


--
-- TOC entry 3692 (class 1259 OID 21320)
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON alugae.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- TOC entry 3695 (class 1259 OID 21304)
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON alugae.account_emailaddress USING btree (user_id);


--
-- TOC entry 3700 (class 1259 OID 21311)
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON alugae.account_emailconfirmation USING btree (email_address_id);


--
-- TOC entry 3701 (class 1259 OID 21310)
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON alugae.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- TOC entry 3665 (class 1259 OID 21253)
-- Name: accounts_customuser_cpf_a7c4889f_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_cpf_a7c4889f_like ON alugae."user" USING btree (cpf varchar_pattern_ops);


--
-- TOC entry 3668 (class 1259 OID 21251)
-- Name: accounts_customuser_email_4fd8e7ce_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_email_4fd8e7ce_like ON alugae."user" USING btree (email varchar_pattern_ops);


--
-- TOC entry 3679 (class 1259 OID 21266)
-- Name: accounts_customuser_groups_customuser_id_bc55088e; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_groups_customuser_id_bc55088e ON alugae.user_groups USING btree (customuser_id);


--
-- TOC entry 3682 (class 1259 OID 21267)
-- Name: accounts_customuser_groups_group_id_86ba5f9e; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_groups_group_id_86ba5f9e ON alugae.user_groups USING btree (group_id);


--
-- TOC entry 3671 (class 1259 OID 21252)
-- Name: accounts_customuser_phone_cd4af485_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_phone_cd4af485_like ON alugae."user" USING btree (phone varchar_pattern_ops);


--
-- TOC entry 3687 (class 1259 OID 21280)
-- Name: accounts_customuser_user_permissions_customuser_id_0deaefae; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_user_permissions_customuser_id_0deaefae ON alugae.user_user_permissions USING btree (customuser_id);


--
-- TOC entry 3688 (class 1259 OID 21281)
-- Name: accounts_customuser_user_permissions_permission_id_aea3d0e5; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_user_permissions_permission_id_aea3d0e5 ON alugae.user_user_permissions USING btree (permission_id);


--
-- TOC entry 3676 (class 1259 OID 21250)
-- Name: accounts_customuser_username_722f3555_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX accounts_customuser_username_722f3555_like ON alugae."user" USING btree (username varchar_pattern_ops);


--
-- TOC entry 3654 (class 1259 OID 21221)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX auth_group_name_a6ea08ec_like ON alugae.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3659 (class 1259 OID 21217)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON alugae.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3662 (class 1259 OID 21218)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON alugae.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3649 (class 1259 OID 21203)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON alugae.auth_permission USING btree (content_type_id);


--
-- TOC entry 3706 (class 1259 OID 21344)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON alugae.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3709 (class 1259 OID 21345)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON alugae.django_admin_log USING btree (user_id);


--
-- TOC entry 3710 (class 1259 OID 21354)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX django_session_expire_date_a5c62663 ON alugae.django_session USING btree (expire_date);


--
-- TOC entry 3713 (class 1259 OID 21353)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX django_session_session_key_c0390e0f_like ON alugae.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3714 (class 1259 OID 21363)
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX django_site_domain_a2e37b91_like ON alugae.django_site USING btree (domain varchar_pattern_ops);


--
-- TOC entry 3775 (class 1259 OID 21869)
-- Name: payment_contract_id_4abcd408; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX payment_contract_id_4abcd408 ON alugae.payment USING btree (contract_id);


--
-- TOC entry 3776 (class 1259 OID 21870)
-- Name: payment_landlord_id_3e830bba; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX payment_landlord_id_3e830bba ON alugae.payment USING btree (landlord_id);


--
-- TOC entry 3779 (class 1259 OID 21871)
-- Name: payment_tenant_id_7947dd62; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX payment_tenant_id_7947dd62 ON alugae.payment USING btree (tenant_id);


--
-- TOC entry 3780 (class 1259 OID 21868)
-- Name: payment_transaction_id_16e2c5ec_like; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX payment_transaction_id_16e2c5ec_like ON alugae.payment USING btree (transaction_id varchar_pattern_ops);


--
-- TOC entry 3783 (class 1259 OID 21872)
-- Name: payment_unit_id_ba083dc2; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX payment_unit_id_ba083dc2 ON alugae.payment USING btree (unit_id);


--
-- TOC entry 3740 (class 1259 OID 21594)
-- Name: property_landlord_id_ef7931a0; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX property_landlord_id_ef7931a0 ON alugae.property USING btree (landlord_id);


--
-- TOC entry 3771 (class 1259 OID 21807)
-- Name: rent_clause_added_by_id_221d7d18; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_clause_added_by_id_221d7d18 ON alugae.rent_clause USING btree (added_by_id);


--
-- TOC entry 3772 (class 1259 OID 21808)
-- Name: rent_clause_contract_id_585d353d; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_clause_contract_id_585d353d ON alugae.rent_clause USING btree (contract_id);


--
-- TOC entry 3759 (class 1259 OID 21782)
-- Name: rent_contract_landlord_id_b114add6; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_contract_landlord_id_b114add6 ON alugae.rent_contract USING btree (landlord_id);


--
-- TOC entry 3762 (class 1259 OID 21795)
-- Name: rent_contract_template_id_f9305d0b; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_contract_template_id_f9305d0b ON alugae.rent_contract USING btree (template_id);


--
-- TOC entry 3763 (class 1259 OID 21796)
-- Name: rent_contract_tenant_id_75a737e4; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_contract_tenant_id_75a737e4 ON alugae.rent_contract USING btree (tenant_id);


--
-- TOC entry 3764 (class 1259 OID 21837)
-- Name: rent_contract_unit_id_bd8e01b6; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_contract_unit_id_bd8e01b6 ON alugae.rent_contract USING btree (unit_id);


--
-- TOC entry 3768 (class 1259 OID 21794)
-- Name: rent_document_contract_id_402dc3c1; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_document_contract_id_402dc3c1 ON alugae.rent_document USING btree (contract_id);


--
-- TOC entry 3765 (class 1259 OID 21788)
-- Name: rent_template_created_by_id_5bda53fc; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX rent_template_created_by_id_5bda53fc ON alugae.rent_template USING btree (created_by_id);


--
-- TOC entry 3723 (class 1259 OID 21401)
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON alugae.socialaccount_socialaccount USING btree (user_id);


--
-- TOC entry 3730 (class 1259 OID 21415)
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON alugae.socialaccount_socialapp_sites USING btree (site_id);


--
-- TOC entry 3731 (class 1259 OID 21414)
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON alugae.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- TOC entry 3732 (class 1259 OID 21426)
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON alugae.socialaccount_socialtoken USING btree (account_id);


--
-- TOC entry 3733 (class 1259 OID 21427)
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON alugae.socialaccount_socialtoken USING btree (app_id);


--
-- TOC entry 3748 (class 1259 OID 21815)
-- Name: tenant_landlord_id_37d21faa; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX tenant_landlord_id_37d21faa ON alugae.tenant USING btree (landlord_id);


--
-- TOC entry 3698 (class 1259 OID 21321)
-- Name: unique_primary_email; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE UNIQUE INDEX unique_primary_email ON alugae.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- TOC entry 3699 (class 1259 OID 21317)
-- Name: unique_verified_email; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE UNIQUE INDEX unique_verified_email ON alugae.account_emailaddress USING btree (email) WHERE verified;


--
-- TOC entry 3743 (class 1259 OID 21595)
-- Name: unit_tenant_id_9873bf43; Type: INDEX; Schema: alugae; Owner: felixmiranda
--

CREATE INDEX unit_tenant_id_9873bf43 ON alugae.unit USING btree (tenant_id);


--
-- TOC entry 3793 (class 2606 OID 21298)
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3794 (class 2606 OID 21305)
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES alugae.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3791 (class 2606 OID 21270)
-- Name: user_user_permissions accounts_customuser__customuser_id_0deaefae_fk_accounts_; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_user_permissions
    ADD CONSTRAINT accounts_customuser__customuser_id_0deaefae_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3789 (class 2606 OID 21256)
-- Name: user_groups accounts_customuser__customuser_id_bc55088e_fk_accounts_; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_groups
    ADD CONSTRAINT accounts_customuser__customuser_id_bc55088e_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3792 (class 2606 OID 21275)
-- Name: user_user_permissions accounts_customuser__permission_id_aea3d0e5_fk_auth_perm; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_user_permissions
    ADD CONSTRAINT accounts_customuser__permission_id_aea3d0e5_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES alugae.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3790 (class 2606 OID 21261)
-- Name: user_groups accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.user_groups
    ADD CONSTRAINT accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES alugae.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3805 (class 2606 OID 21528)
-- Name: tenant accounts_tenant_user_id_81dc247d_fk_user_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.tenant
    ADD CONSTRAINT accounts_tenant_user_id_81dc247d_fk_user_id FOREIGN KEY (user_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3808 (class 2606 OID 21899)
-- Name: adoption_codes adoption_codes_landlord_id_d0575cd2_fk_landlord_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.adoption_codes
    ADD CONSTRAINT adoption_codes_landlord_id_d0575cd2_fk_landlord_id FOREIGN KEY (landlord_id) REFERENCES alugae.landlord(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3787 (class 2606 OID 21212)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES alugae.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3788 (class 2606 OID 21207)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES alugae.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3786 (class 2606 OID 21198)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES alugae.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3795 (class 2606 OID 21334)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES alugae.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3796 (class 2606 OID 21339)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_id FOREIGN KEY (user_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3803 (class 2606 OID 21721)
-- Name: unit fk_property; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.unit
    ADD CONSTRAINT fk_property FOREIGN KEY (property_id) REFERENCES alugae.property(id) ON DELETE CASCADE;


--
-- TOC entry 3807 (class 2606 OID 21634)
-- Name: landlord fk_user; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.landlord
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES alugae."user"(id) ON DELETE CASCADE;


--
-- TOC entry 3817 (class 2606 OID 21848)
-- Name: payment payment_contract_id_4abcd408_fk_rent_contract_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.payment
    ADD CONSTRAINT payment_contract_id_4abcd408_fk_rent_contract_id FOREIGN KEY (contract_id) REFERENCES alugae.rent_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3818 (class 2606 OID 21853)
-- Name: payment payment_landlord_id_3e830bba_fk_landlord_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.payment
    ADD CONSTRAINT payment_landlord_id_3e830bba_fk_landlord_id FOREIGN KEY (landlord_id) REFERENCES alugae.landlord(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3819 (class 2606 OID 21858)
-- Name: payment payment_tenant_id_7947dd62_fk_tenant_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.payment
    ADD CONSTRAINT payment_tenant_id_7947dd62_fk_tenant_id FOREIGN KEY (tenant_id) REFERENCES alugae.tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3820 (class 2606 OID 21863)
-- Name: payment payment_unit_id_ba083dc2_fk_unit_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.payment
    ADD CONSTRAINT payment_unit_id_ba083dc2_fk_unit_id FOREIGN KEY (unit_id) REFERENCES alugae.unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3802 (class 2606 OID 21826)
-- Name: property properties_property_landlord_id_fk_landlord_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.property
    ADD CONSTRAINT properties_property_landlord_id_fk_landlord_id FOREIGN KEY (landlord_id) REFERENCES alugae.landlord(id) ON DELETE CASCADE;


--
-- TOC entry 3804 (class 2606 OID 21588)
-- Name: unit properties_unit_tenant_id_b85f3330_fk_tenant_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.unit
    ADD CONSTRAINT properties_unit_tenant_id_b85f3330_fk_tenant_id FOREIGN KEY (tenant_id) REFERENCES alugae.tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3815 (class 2606 OID 21797)
-- Name: rent_clause rent_clause_added_by_id_221d7d18_fk_user_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_clause
    ADD CONSTRAINT rent_clause_added_by_id_221d7d18_fk_user_id FOREIGN KEY (added_by_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3816 (class 2606 OID 21802)
-- Name: rent_clause rent_clause_contract_id_585d353d_fk_rent_contract_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_clause
    ADD CONSTRAINT rent_clause_contract_id_585d353d_fk_rent_contract_id FOREIGN KEY (contract_id) REFERENCES alugae.rent_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3809 (class 2606 OID 21777)
-- Name: rent_contract rent_contract_landlord_id_b114add6_fk_user_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_contract
    ADD CONSTRAINT rent_contract_landlord_id_b114add6_fk_user_id FOREIGN KEY (landlord_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3810 (class 2606 OID 21759)
-- Name: rent_contract rent_contract_template_id_f9305d0b_fk_rent_template_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_contract
    ADD CONSTRAINT rent_contract_template_id_f9305d0b_fk_rent_template_id FOREIGN KEY (template_id) REFERENCES alugae.rent_template(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3811 (class 2606 OID 21764)
-- Name: rent_contract rent_contract_tenant_id_75a737e4_fk_user_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_contract
    ADD CONSTRAINT rent_contract_tenant_id_75a737e4_fk_user_id FOREIGN KEY (tenant_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3812 (class 2606 OID 21832)
-- Name: rent_contract rent_contract_unit_id_bd8e01b6_fk_unit_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_contract
    ADD CONSTRAINT rent_contract_unit_id_bd8e01b6_fk_unit_id FOREIGN KEY (unit_id) REFERENCES alugae.unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3814 (class 2606 OID 21789)
-- Name: rent_document rent_document_contract_id_402dc3c1_fk_rent_contract_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_document
    ADD CONSTRAINT rent_document_contract_id_402dc3c1_fk_rent_contract_id FOREIGN KEY (contract_id) REFERENCES alugae.rent_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3813 (class 2606 OID 21783)
-- Name: rent_template rent_template_created_by_id_5bda53fc_fk_user_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.rent_template
    ADD CONSTRAINT rent_template_created_by_id_5bda53fc_fk_user_id FOREIGN KEY (created_by_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3800 (class 2606 OID 21416)
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES alugae.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3801 (class 2606 OID 21434)
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES alugae.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3798 (class 2606 OID 21409)
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES alugae.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3799 (class 2606 OID 21404)
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES alugae.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3797 (class 2606 OID 21396)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_user_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_user_id FOREIGN KEY (user_id) REFERENCES alugae."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3806 (class 2606 OID 21810)
-- Name: tenant tenant_landlord_id_37d21faa_fk_landlord_id; Type: FK CONSTRAINT; Schema: alugae; Owner: felixmiranda
--

ALTER TABLE ONLY alugae.tenant
    ADD CONSTRAINT tenant_landlord_id_37d21faa_fk_landlord_id FOREIGN KEY (landlord_id) REFERENCES alugae.landlord(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3965 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: felixmiranda
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2025-03-06 09:10:33 -03

--
-- PostgreSQL database dump complete
--

