"""
Django settings for alugAE project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Initialize django-environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z#c2$8dvb3h8@sty%mwo+!!j650e44k_t)bg-x4m7$b(86zq9n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '.railway.app', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    # Native 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps creation
    'accounts',
    'properties',
    'payments',
    'rent',
    # Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_framework', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'alugAE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alugAE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'alugae',  # Nome do banco de dados
#         'USER': 'felixmiranda',  # Usuário do banco de dados
#         'PASSWORD': 'go',  # Senha do usuário
#         'HOST': 'localhost',  # Endereço do banco de dados
#         'PORT': '5432',  # Porta do PostgreSQL
#         'OPTIONS': {
#             'options': '-c search_path=alugae'  # Configura o schema padrão
#         },
#     }
# }

DATABASES = {
    'default': env.db('DATABASE_URL', default='postgresql://postgres:cwPEnbhRBqwEACGwXQPYQGRHzzHANxvh@trolley.proxy.rlwy.net:17985/railway?schema=alugae')
}

MIGRATION_MODULES = {
    'accounts': None,
    'properties': None,
    'payments': None,
    'rent': None,
    'account': None,  # Ignora migrações do app 'account'
    'admin': None,  # Ignora migrações do app 'admin'
    'auth': None,  # Ignora migrações do app 'auth'
    'contenttypes': None,  # Ignora migrações do app 'contenttypes'
    'sessions': None,  # Ignora migrações do app 'sessions'
    'sites': None,  # Ignora migrações do app 'sites'
    'socialaccount': None,  # Ignora migrações do app 'socialaccount'

    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "accounts.CustomUser"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.CustomAuthenticationBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ACCOUNT_FORMS = {
    "login": "accounts.forms.CustomLoginForm",
}

SITE_ID = 1

# Configurações de Autenticação do django-allauth
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Vamos customizar para incluir telefone
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # Em segundos (5 minutos)

LOGOUT_REDIRECT_URL = '/accounts/login/'  # Redireciona para a página de login

LOGIN_URL = '/accounts/login/'  # Página para redirecionar usuários não autenticados
LOGIN_REDIRECT_URL = '/accounts/profile/'  # Página para redirecionar após login bem-sucedido

# Media settings
MEDIA_URL = '/media/'  # URL base para acessar os arquivos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')  # Diretório raiz para arquivos

# Subdiretório para templates de contratos
CONTRACTS_TEMPLATES_DIR = os.path.join(MEDIA_ROOT, 'contracts_templates/')


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


import environ

# Inicializa o objeto de ambiente
env = environ.Env()
environ.Env.read_env()  # Lê as variáveis do arquivo .env

# Defina as configurações de arquivos estáticos
STATIC_URL = env('STATIC_URL', default='/static/')
STATIC_ROOT = env('STATIC_ROOT', default='staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
