"""
Django settings for alugAE project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Initialize django-environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '.railway.app', '127.0.0.1', 'alugae-production.up.railway.app']

CSRF_TRUSTED_ORIGINS = [
    'https://alugae-production.up.railway.app',  # Adicione o domínio do seu aplicativo
]

# Application definition

INSTALLED_APPS = [
    # Native 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps creation
    'accounts',
    'properties',
    'payments',
    'rent',
    # Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_framework',
    'django_celery_beat', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    "csp.middleware.CSPMiddleware", 
]

# Permitir o Maze como fonte confiável
CSP_DEFAULT_SRC = ["'self'", "https://*.maze.co"]
CSP_SCRIPT_SRC = ["'self'", "https://snippet.maze.co", "'unsafe-inline'"]
CSP_FONT_SRC = ["'self'", "https://snippet.maze.co", "https://fonts.gstatic.com"]
CSP_STYLE_SRC = ["'self'", "https://snippet.maze.co", "https://fonts.googleapis.com", "'unsafe-inline'"]
CSP_IMG_SRC = ["'self'", "https://snippet.maze.co"]
CSP_CONNECT_SRC = ["'self'", "https://api.maze.co", "https://prompts.maze.co"]
CSP_FRAME_SRC = ["'self'", "https://t.maze.co"]


ROOT_URLCONF = 'alugAE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alugAE.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'alugae',  # Nome do banco de dados
        'USER': 'felixmiranda',  # Usuário do banco de dados
        'PASSWORD': 'go',  # Senha do usuário
        'HOST': 'localhost',  # Endereço do banco de dados
        'PORT': '5432',  # Porta do PostgreSQL
        'OPTIONS': {
            'options': '-c search_path=alugae'  # Configura o schema padrão
        },
    }
}

# DATABASES = {
#     'default': env.db('DATABASE_URL', default='postgresql://postgres:cwPEnbhRBqwEACGwXQPYQGRHzzHANxvh@trolley.proxy.rlwy.net:17985/railway?schema=alugae')
# }

MIGRATION_MODULES = {
    'accounts': None,
    'properties': None,
    'payments': None,
    'rent': None,
    'account': None,  # Ignora migrações do app 'account'
    'admin': None,  # Ignora migrações do app 'admin'
    'auth': None,  # Ignora migrações do app 'auth'
    'contenttypes': None,  # Ignora migrações do app 'contenttypes'
    'sessions': None,  # Ignora migrações do app 'sessions'
    'sites': None,  # Ignora migrações do app 'sites'
    'socialaccount': None,  # Ignora migrações do app 'socialaccount'

    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "accounts.CustomUser"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.CustomAuthenticationBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ACCOUNT_FORMS = {
    "login": "accounts.forms.CustomLoginForm",
}

SITE_ID = 1

# Configurações de Autenticação do django-allauth
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Vamos customizar para incluir telefone
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # Em segundos (5 minutos)

LOGOUT_REDIRECT_URL = '/accounts/login/'  # Redireciona para a página de login

LOGIN_URL = '/accounts/login/'  # Página para redirecionar usuários não autenticados
LOGIN_REDIRECT_URL = '/accounts/profile/'  # Página para redirecionar após login bem-sucedido

# Media settings
MEDIA_URL = '/media/'  # URL base para acessar os arquivos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')  # Diretório raiz para arquivos

# Subdiretório para templates de contratos
CONTRACTS_TEMPLATES_DIR = os.path.join(MEDIA_ROOT, 'contracts_templates/')

#TWILIO variables
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN')
TWILIO_WHATSAPP_NUMBER = env('TWILIO_WHATSAPP_NUMBER')

TWILIO_TEMPLATE_PAYMENT_REMINDER_3DAYS = env('TWILIO_TEMPLATE_PAYMENT_REMINDER_3DAYS', default='')
TWILIO_TEMPLATE_PAYMENT_REMINDER_DUEDATE = env('TWILIO_TEMPLATE_PAYMENT_REMINDER_DUEDATE', default='')
TWILIO_TEMPLATE_PAYMENT_REMINDER_1DAY = env('TWILIO_TEMPLATE_PAYMENT_REMINDER_1DAY', default='')
TWILIO_TEMPLATE_PROOF_RECEIVED = env('TWILIO_TEMPLATE_PROOF_RECEIVED', default='')
TWILIO_TEMPLATE_APPROVED = env('TWILIO_TEMPLATE_APPROVED', default='')
TWILIO_TEMPLATE_REJECTED = env('TWILIO_TEMPLATE_REJECTED', default='')

#Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# STATIC_URL = '/static/'

# # Configuração de arquivos estáticos com o WhiteNoise
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # Diretório onde os arquivos estáticos serão coletados em produção
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = 'static/'

# 🛠️ Corrigindo para garantir que Django encontre os arquivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Adiciona a pasta static como diretório válido
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Onde os arquivos serão coletados

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
