# Generated by Django 5.1.5 on 2025-01-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_unit_id'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.unit'),
            preserve_default=False,
        ),
    ]
