# Generated by Django 4.2.17 on 2024-12-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_created_at_alter_tenant_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenant',
            table='tenant',
        ),
    ]
