# Generated by Django 4.2.17 on 2024-12-27 16:29

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('accounts', '0005_alter_tenant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioncode',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Adoption Code'),
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.default_expiration, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is Used'),
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_codes', to=settings.AUTH_USER_MODEL, verbose_name='Landlord'),
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_codes_property', to='properties.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_codes_unit', to='properties.unit', verbose_name='Unit'),
        ),
    ]
