# Generated by Django 4.2.17 on 2024-12-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_adoptioncode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='accounts.landlord', verbose_name='Landlord'),
            preserve_default=False,
        ),
    ]
