# Generated by Django 5.1.5 on 2025-02-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenant_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
