# Generated by Django 5.1.5 on 2025-02-27 21:04

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_landlord_pix_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptioncode',
            options={},
        ),
        migrations.RemoveField(
            model_name='adoptioncode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adoptioncode',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='adoptioncode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='adoptioncode',
            name='property',
        ),
        migrations.RemoveField(
            model_name='adoptioncode',
            name='unit',
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='code',
            field=models.CharField(default=accounts.models.generate_adoption_code, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='adoptioncode',
            name='landlord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
