# Generated by Django 5.1.5 on 2025-02-27 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_adoptioncode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioncode',
            name='landlord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_code', to='accounts.landlord'),
        ),
    ]
