# Generated by Django 4.2.17 on 2024-12-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_unit_created_at_unit_id_unit_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='property_ptr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='unit', to='properties.property', verbose_name='Property Reference'),
        ),
    ]
