# Generated by Django 4.2.17 on 2024-12-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_unit_property_ptr_unit_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
